In [4]:
import os
import pandas as pd
import geopandas as gpd

In [6]:
input_folder = os.path.join('..', '..', '..', 'Ecuador', 'Data', 'Structured')
output_folder = os.path.join('..', 'input', 'Ecuador', 'Supply')

# Load Canton

In [51]:
canton = gpd.read_file(os.path.join(input_folder, "Admin", "canton_cities.geojson"))
print(canton['DPA_CANTON'].duplicated().sum())
canton = canton.drop_duplicates(subset=['DPA_CANTON']) #en attendant de mieux choisir
print(canton['DPA_CANTON'].duplicated().sum())
canton

23
0

,province_code,province_name,city_code,canton_name,index_right,DPA_CANTON,DPA_PROVIN,DPA_DESPRO,DPA_DESCAN,Leyend,Agri_prod,geometry
0,107,EL ORO,10701,MACHALA,52.0,0701,07,EL ORO,MACHALA,07-01 MACHALA,2.003842e+08,POINT (614953.198 9638638.887)
1,107,EL ORO,10702,ARENILLAS,53.0,0702,07,EL ORO,ARENILLAS,07-02 ARENILLAS,1.769213e+08,POINT (603167.277 9606366.207)
2,107,EL ORO,10703,ATAHUALPA,54.0,0703,07,EL ORO,ATAHUALPA,07-03 ATAHUALPA,1.102533e+07,POINT (650186.519 9602870.267)
3,107,EL ORO,10704,BALSAS,55.0,0704,07,EL ORO,BALSAS,07-04 BALSAS,3.920469e+06,POINT (629523.996 9583446.404)
4,107,EL ORO,10705,CHILLA,56.0,0705,07,EL ORO,CHILLA,07-05 CHILLA,2.682141e+07,POINT (656358.781 9617770.034)
...,...,...,...,...,...,...,...,...,...,...,...,...
221,322,ORELLANA,32203,LA JOYA DE LOS SACHAS,213.0,2203,22,ORELLANA,LA JOYA DE LOS SACHAS,22-03 LA JOYA DE LOS SACHAS,7.540929e+07,POINT (960853.342 9967173.385)
222,322,ORELLANA,32204,LORETO,214.0,2204,22,ORELLANA,LORETO,22-04 LORETO,6.424504e+06,POINT (909049.510 9923875.875)
223,420,GALAPAGOS,42001,SAN CRISTOBAL,223.0,2001,20,GALAPAGOS,SAN CRISTOBAL,20-01 SAN CRISTOBAL,1.334000e+03,POINT (-461487.883 9898833.798)
224,420,GALAPAGOS,42002,ISABELA,222.0,2002,20,GALAPAGOS,ISABELA,20-02 ISABELA,1.204000e+03,POINT (-614305.361 9892767.940)
225,420,GALAPAGOS,42003,SANTA CRUZ,224.0,2003,20,GALAPAGOS,SANTA CRUZ,20-03 SANTA CRUZ,6.674000e+03,POINT (-541000.911 9917135.159)

# Add agri

In [52]:
agri = gpd.read_file(os.path.join(input_folder, "Supply", "agri.geojson"))
print(agri['DPA_CANTON'].duplicated().sum())
canton['agri_prod'] = canton['DPA_CANTON'].map(agri.groupby('DPA_CANTON')['Agri_prod'].sum())
canton

1

,province_code,province_name,city_code,canton_name,index_right,DPA_CANTON,DPA_PROVIN,DPA_DESPRO,DPA_DESCAN,Leyend,Agri_prod,geometry,agri_prod
0,107,EL ORO,10701,MACHALA,52.0,0701,07,EL ORO,MACHALA,07-01 MACHALA,2.003842e+08,POINT (614953.198 9638638.887),2.003842e+08
1,107,EL ORO,10702,ARENILLAS,53.0,0702,07,EL ORO,ARENILLAS,07-02 ARENILLAS,1.769213e+08,POINT (603167.277 9606366.207),1.769213e+08
2,107,EL ORO,10703,ATAHUALPA,54.0,0703,07,EL ORO,ATAHUALPA,07-03 ATAHUALPA,1.102533e+07,POINT (650186.519 9602870.267),1.102533e+07
3,107,EL ORO,10704,BALSAS,55.0,0704,07,EL ORO,BALSAS,07-04 BALSAS,3.920469e+06,POINT (629523.996 9583446.404),3.920469e+06
4,107,EL ORO,10705,CHILLA,56.0,0705,07,EL ORO,CHILLA,07-05 CHILLA,2.682141e+07,POINT (656358.781 9617770.034),2.682141e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,322,ORELLANA,32203,LA JOYA DE LOS SACHAS,213.0,2203,22,ORELLANA,LA JOYA DE LOS SACHAS,22-03 LA JOYA DE LOS SACHAS,7.540929e+07,POINT (960853.342 9967173.385),7.540929e+07
222,322,ORELLANA,32204,LORETO,214.0,2204,22,ORELLANA,LORETO,22-04 LORETO,6.424504e+06,POINT (909049.510 9923875.875),6.424504e+06
223,420,GALAPAGOS,42001,SAN CRISTOBAL,223.0,2001,20,GALAPAGOS,SAN CRISTOBAL,20-01 SAN CRISTOBAL,1.334000e+03,POINT (-461487.883 9898833.798),1.334000e+03
224,420,GALAPAGOS,42002,ISABELA,222.0,2002,20,GALAPAGOS,ISABELA,20-02 ISABELA,1.204000e+03,POINT (-614305.361 9892767.940),1.204000e+03
225,420,GALAPAGOS,42003,SANTA CRUZ,224.0,2003,20,GALAPAGOS,SANTA CRUZ,20-03 SANTA CRUZ,6.674000e+03,POINT (-541000.911 9917135.159),6.674000e+03

# Add other sectors

In [53]:
sectors = pd.read_csv(os.path.join(input_folder, "Sectors", "sectors.csv"))
supply = gpd.read_file(os.path.join(input_folder, "Supply", "all_2015.geojson"))
print(supply['DPA_CANTON'].duplicated().sum())
supply.head()

1

,DPA_CANTON,DPA_PROVIN,DPA_DESPRO,DPA_DESCAN,Leyend,Agri_prod,canton,target_9,target_A,target_B,...,source_O,source_P,source_Q,source_R-S,source_T,source_U,source_V,source_W,source_X,geometry
0,0101,01,AZUAY,CUENCA,01-01 CUENCA,3.111493e+06,101,NaN,48466.41808,24389.59595,...,16085.65602,15338.21887,82614.25932,46178.42428,670.70308,31.08200,67.79722,581.56189,46.74661,"POLYGON ((682457.572 9716225.007, 682784.909 9..."
1,0102,01,AZUAY,GIRON,01-02 GIRON,0.000000e+00,102,NaN,182.11233,370.15697,...,52.97667,8.72998,22.61606,118.02602,12.73068,21.37000,NaN,NaN,NaN,"POLYGON ((696928.442 9661026.377, 696958.860 9..."
2,0103,01,AZUAY,GUALACEO,01-03 GUALACEO,0.000000e+00,103,NaN,967.07168,40.39184,...,305.57455,22.07284,582.55360,617.02071,17.22755,0.80135,NaN,NaN,1.00112,"POLYGON ((756004.754 9689467.552, 756135.820 9..."
3,0104,01,AZUAY,NABON,01-04 NABON,3.569428e+05,104,NaN,75.73560,NaN,...,2.00589,2.11931,3.49193,378.41507,5.64594,NaN,NaN,NaN,3.35000,"POLYGON ((721857.501 9644366.092, 721872.277 9..."
4,0105,01,AZUAY,PAUTE,01-05 PAUTE,0.000000e+00,105,NaN,3624.94741,1722.00114,...,451.52507,32.13126,28.69615,913.90934,8.23650,NaN,NaN,15.57921,NaN,"POLYGON ((764977.660 9707086.419, 764977.660 9..."

In [54]:
for sector, letter in sectors.set_index('trigram')['letter'].to_dict().items():
    canton['source_'+sector] = canton['DPA_CANTON'].map(supply.groupby('DPA_CANTON')['source_'+letter].sum())

# Pop

In [56]:
canton['population'] = 10000

# Export

In [57]:
canton.to_file(os.path.join(output_folder, "canton_economic_data.geojson"), driver="GeoJSON")